### ISSUE TITLE
[TODO] rid of static font colours

### ISSUE THREAD

**Issue by Kashargul** [VOREStation/VOREStation#15693]
Statically used text colors for chat messages are causing issues with some darker themes. Furthermore they complicate the implementation of a color blind theme.

- [x] Test old chat css tag compatibility
- [x] Test tg-chat filters with class color labels
- [x] Migrate all font tags to class labels
- [x] Verify all color css tags in the 4 tg-chat themes
~~- [ ] Change CI to error on font tags (deprecated warning)~~ Not possible, some UI element use static tags, not gonna touch them.
