### ISSUE TITLE
Meta-human species (colorable humans)

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#388]
#### Brief description of the issue
We don't have a human species that can be re-colored to one's own desires. We need to fix this. Rather than make the human species color-able, which creates compatibility issues, let's make a new species.

This issue replaces https://github.com/VOREStation/VOREStation/issues/163

Sprites for meta-humans exist in the old vorestation code. However it would be better if we had dark sprite version so we can use THE CORRECT RGB formatting instead of the old badly done grayscale one.

- [ ] Recolor human sprites to be black based, so they can be recolored correctly.
- [ ] Add new species for meta-humans.
- [ ] Add species compatibility with any suits that allow human occupants (if necessary)
